### ISSUE TITLE
[Bug]: Can't Create Post Threads

### ISSUE THREAD

**Issue by aaronvegh** [MasterJ93/ATProtoKit#32] opened 2024-09-09 00:05 UTC
### Summary

Using the `replyTo` parameter in `createPostRecord` with the URL of a previous post results in an error.

### Reproduction Steps

I am writing an app that fires Post objects. When the number of objects is greater than one, I store the StrongReference of the previous post, so I can use the `recordURI` result as the value in the `replyTo` property for the subsequent post.

I found these calls were resulting in errors, complaining about malformed URIs. 

### Expected Results

I was hoping the reply post in the thread would successfully publish.

### Actual Results

I got the error stated above.

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS, Other

### Operating System Version

On Xcode 16 beta 6 in a simulator running iOS 18. 

### ATProtoKit Version

Current main 0.17.5

**Comment by MasterJ93** [comment] 2024-09-09 02:35
Interesting. I saw that you've made a PR as well. I'll be releasing a newer version of ATProtoKit before the week is over. Once that's done, I would suggest that you look at your PR and update things. From a quick skim through your code, some of the things that you've fixed are actually in my update, hence why I'm making this suggestion.

Thanks for submitting this. I'll have to test out your code to make sure things are working correctly after you update it with my changes.

**Comment by aaronvegh** [comment] 2024-09-09 13:10
Thank you. Please let me know when you do that and I'll update! 🙌

**Comment by aaronvegh** [comment] 2024-09-26 00:56
@MasterJ93 Do you have an update on this?

**Comment by MasterJ93** [comment] 2024-09-26 12:40
Sorry for the late reply.

There's a bug with respect to uploading the videos and I'm trying to get this resolved. I've been spending all day and night yesterday to figure it out. Once I have that fixed, I'll release the update.

**Comment by MasterJ93** [comment] 2024-10-18 06:07
Sorry for the extremely long delay: I didn't think it would take this long to get uploading videos to work. But version 0.18.1 is now out.

Please look at your pull request and update it in order to prevent any conflicts.

**Comment by aaronvegh** [comment] 2024-10-18 13:16
@MasterJ93 Just pushed to resolve the conflict, thank you!

**Comment by MasterJ93** [comment] 2024-10-19 07:39
I've merged the relevant pull request and it's now released in the latest hotfix, so I'm going to close this issue. If the issue is still happening, please feel free to create a new issue or re-open this. Thanks for your bug fix!

**Closed by MasterJ93** 2024-10-19 07:39 UTC
Labels: bug
