### ISSUE TITLE
[Bug]: UTF-8 Characters Upset Parsing

### ISSUE THREAD

**Issue by aaronvegh** [MasterJ93/ATProtoKit#35] opened 2024-10-03 00:06 UTC
### Summary

Using non-ASCII characters in the post text messes up marking of links and hashtags.

### Reproduction Steps

Fire a string that contains non-ascii strings, including smart quotes/apostrophes, accented vowels, emoji, and also includes inline hashtags and links. When they appear on Bluesky, the ranges of the appropriate hashtags are incorrect. 

### Expected Results

When I stripped the text of emojis and accented characters, it yields a correctly-parsed message: 

https://bsky.app/profile/aaronvegh.bsky.social/post/3l5kwyovfit2x

### Actual Results

Here's an example:

https://bsky.app/profile/pixelgraphix.de/post/3l5jdjjin3g2j

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS

### Operating System Version

iOS 17-18

### ATProtoKit Version

0.17.5

**Comment by MasterJ93** [comment] 2024-10-19 07:41
The relevant pull request has been merged and is included with version 0.18.2. Thanks for the fix. I'm closing this issue now but feel free to re-open it if the issue is still happening. Of course, you're more than welcome to make suggestions.

**Closed by MasterJ93** 2024-10-19 07:41 UTC
Labels: bug
