### ISSUE TITLE
[Bug]: ATProtoKit.getProfile Return Type

### ISSUE THREAD

**Issue by JoshuaHolme** [MasterJ93/ATProtoKit#25] opened 2024-06-22 15:16 UTC
### Summary

The get profile function has a deserialization error

### Reproduction Steps

Call `ATProtoKit.getProfile` and try to assign it to the expected type of `AppBskyLexicon.Actor.GetProfileOutput`

### Expected Results

I expect the object to save correctly and be able to access `actorProfileView` on it, and then access the parameters of `ProfileViewDetailedDefinition` through that.

### Actual Results

The call fails because it couldn't find coding keys for `actorProfileView`

### What operating systems did you experience this bug? (We'll count Docker as an operating system.)

macOS, Other

### Operating System Version

iOS 17

### ATProtoKit Version

0.14.2

### Additional Context

Changing the return type to `ProfileViewDetailedDefinition` directly allows the call to succeed and lets you access the data without issue

**Comment by JoshuaHolme** [comment] 2024-06-23 01:01
There seems to be a similar issue with `getAuthorFeed`. I get the following error when trying to call that:

```
DecodingError
  ▿ keyNotFound : 2 elements
    - .0 : CodingKeys(stringValue: "knownFollowers", intValue: nil)
    ▿ .1 : Context
      ▿ codingPath : 5 elements
        - 0 : CodingKeys(stringValue: "feed", intValue: nil)
        ▿ 1 : _JSONKey(stringValue: "Index 0", intValue: 0)
          ▿ rep : Rep
            - index : 0
        - 2 : CodingKeys(stringValue: "post", intValue: nil)
        - 3 : CodingKeys(stringValue: "author", intValue: nil)
        - 4 : CodingKeys(stringValue: "viewer", intValue: nil)
      - debugDescription : "No value associated with key CodingKeys(stringValue: \"knownFollowers\", intValue: nil) (\"knownFollowers\")."
      - underlyingError : nil
```

**Comment by JoshuaHolme** [comment] 2024-06-23 01:04
And looking at postman it doesn't seem like this call gets `knownFollowers` back. I also don't see it on the return model for `getAuthorFeed` so I don't know where it's coming from

**Comment by MasterJ93** [comment] 2024-06-23 01:40
This is something that will require me to dig deeper into Bluesky's lexicons. Hopefully I can resolve this tomorrow or Monday. But taking a quick view of the model and method, it doesn't look like `knownFollowers shouldn't even appear.

Do you mind giving me the error in full, as well as the Postman response?

**Comment by JoshuaHolme** [comment] 2024-06-23 07:31
Here is the first object in the postman so it's not too long. That also was the entire error that I pasted in my previous comment
```
{
    "feed": [
        {
            "post": {
                "uri": "at://did:plc:5ikuok36ktskewx5l6xcshtg/app.bsky.feed.post/3kvjq35npgs2s",
                "cid": "bafyreihvqjsuw5lvux5dxmh6jqqdxuyawmeuluzrryh2hm5crkwdhfgej4",
                "author": {
                    "did": "did:plc:5ikuok36ktskewx5l6xcshtg",
                    "handle": "josh.holme.social",
                    "displayName": "Josh Holme",
                    "avatar": "https://cdn.bsky.app/img/avatar/plain/did:plc:5ikuok36ktskewx5l6xcshtg/bafkreihfl357xsaeghxuvex3cjaagfwkb3brhkdx532pcebznkvnxvvhy4@jpeg",
                    "associated": {
                        "chat": {
                            "allowIncoming": "following"
                        }
                    },
                    "viewer": {
                        "muted": false,
                        "blockedBy": false
                    },
                    "labels": [],
                    "createdAt": "0001-01-01T00:00:00.000Z"
                },
                "record": {
                    "$type": "app.bsky.feed.post",
                    "createdAt": "2024-06-22T17:02:09.928Z",
                    "langs": [
                        "en"
                    ],
                    "reply": {
                        "parent": {
                            "cid": "bafyreidy6iq2fgano5tv32vri4bfa2pqoorg4pexlal44x3abruf2bjpoi",
                            "uri": "at://did:plc:ia76kvnndjutgedggx2ibrem/app.bsky.feed.post/3kviglz7qjsfr"
                        },
                        "root": {
                            "cid": "bafyreiflwzuatocvixdyie5vh6poag4aamy7j33yadfrprxtvglcg7szzi",
                            "uri": "at://did:plc:oisofpd7lj26yvgiivf3lxsi/app.bsky.feed.post/3kvigizd6cm2m"
                        }
                    },
                    "text": "Is this just improved onboarding with suggested follows and suggest account setup actions?"
                },
                "replyCount": 0,
                "repostCount": 0,
                "likeCount": 0,
                "indexedAt": "2024-06-22T17:02:09.928Z",
                "viewer": {
                    "threadMuted": false
                },
                "labels": []
            },
            "reply": {
                "root": {
                    "$type": "app.bsky.feed.defs#postView",
                    "uri": "at://did:plc:oisofpd7lj26yvgiivf3lxsi/app.bsky.feed.post/3kvigizd6cm2m",
                    "cid": "bafyreiflwzuatocvixdyie5vh6poag4aamy7j33yadfrprxtvglcg7szzi",
                    "author": {
                        "did": "did:plc:oisofpd7lj26yvgiivf3lxsi",
                        "handle": "haileyok.com",
                        "displayName": "hailey",
                        "avatar": "https://cdn.bsky.app/img/avatar/plain/did:plc:oisofpd7lj26yvgiivf3lxsi/bafkreia4lpswywb5yx3gsezqb5io73kt7icw634ks4m4mmbfvp7e62cxku@jpeg",
                        "associated": {
                            "chat": {
                                "allowIncoming": "all"
                            }
                        },
                        "viewer": {
                            "muted": false,
                            "blockedBy": false
                        },
                        "labels": [],
                        "createdAt": "0001-01-01T00:00:00.000Z"
                    },
                    "record": {
                        "$type": "app.bsky.feed.post",
                        "createdAt": "2024-06-22T04:38:17.860Z",
                        "embed": {
                            "$type": "app.bsky.embed.images",
                            "images": [
                                {
                                    "alt": "a github diff, that shows 6,329 additions and 230 deletions",
                                    "aspectRatio": {
                                        "height": 192,
                                        "width": 386
                                    },
                                    "image": {
                                        "$type": "blob",
                                        "ref": {
                                            "$link": "bafkreidlwzxchfwapydcqy3kgcru23abcsqhcxe2z7krnngjeenzjg57ve"
                                        },
                                        "mimeType": "image/jpeg",
                                        "size": 16656
                                    }
                                },
                                {
                                    "alt": "a button that says \"squash and merge\"",
                                    "aspectRatio": {
                                        "height": 404,
                                        "width": 476
                                    },
                                    "image": {
                                        "$type": "blob",
                                        "ref": {
                                            "$link": "bafkreieac4pk2ktut6fkwkomfbzmhvscvp4dpqgbqs42epzivkvwddozmy"
                                        },
                                        "mimeType": "image/jpeg",
                                        "size": 64099
                                    }
                                }
                            ]
                        },
                        "langs": [
                            "en"
                        ],
                        "text": "whew"
                    },
                    "embed": {
                        "$type": "app.bsky.embed.images#view",
                        "images": [
                            {
                                "thumb": "https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:oisofpd7lj26yvgiivf3lxsi/bafkreidlwzxchfwapydcqy3kgcru23abcsqhcxe2z7krnngjeenzjg57ve@jpeg",
                                "fullsize": "https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:oisofpd7lj26yvgiivf3lxsi/bafkreidlwzxchfwapydcqy3kgcru23abcsqhcxe2z7krnngjeenzjg57ve@jpeg",
                                "alt": "a github diff, that shows 6,329 additions and 230 deletions",
                                "aspectRatio": {
                                    "height": 192,
                                    "width": 386
                                }
                            },
                            {
                                "thumb": "https://cdn.bsky.app/img/feed_thumbnail/plain/did:plc:oisofpd7lj26yvgiivf3lxsi/bafkreieac4pk2ktut6fkwkomfbzmhvscvp4dpqgbqs42epzivkvwddozmy@jpeg",
                                "fullsize": "https://cdn.bsky.app/img/feed_fullsize/plain/did:plc:oisofpd7lj26yvgiivf3lxsi/bafkreieac4pk2ktut6fkwkomfbzmhvscvp4dpqgbqs42epzivkvwddozmy@jpeg",
                                "alt": "a button that says \"squash and merge\"",
                                "aspectRatio": {
                                    "height": 404,
                                    "width": 476
                                }
                            }
                        ]
                    },
                    "replyCount": 7,
                    "repostCount": 2,
                    "likeCount": 36,
                    "indexedAt": "2024-06-22T04:38:17.860Z",
                    "viewer": {
                        "threadMuted": false
                    },
                    "labels": []
                },
                "parent": {
                    "$type": "app.bsky.feed.defs#postView",
                    "uri": "at://did:plc:ia76kvnndjutgedggx2ibrem/app.bsky.feed.post/3kviglz7qjsfr",
                    "cid": "bafyreidy6iq2fgano5tv32vri4bfa2pqoorg4pexlal44x3abruf2bjpoi",
                    "author": {
                        "did": "did:plc:ia76kvnndjutgedggx2ibrem",
                        "handle": "mary.my.id",
                        "displayName": "mary🐇",
                        "avatar": "https://cdn.bsky.app/img/avatar/plain/did:plc:ia76kvnndjutgedggx2ibrem/bafkreiesgyo7ukzqhs5mmtulvovzrbbru7ztvopwdwfsvllu553qgfmxd4@jpeg",
                        "associated": {
                            "chat": {
                                "allowIncoming": "all"
                            }
                        },
                        "viewer": {
                            "muted": false,
                            "blockedBy": false
                        },
                        "labels": [],
                        "createdAt": "0001-01-01T00:00:00.000Z"
                    },
                    "record": {
                        "$type": "app.bsky.feed.post",
                        "createdAt": "2024-06-22T04:39:58.000Z",
                        "facets": [],
                        "langs": [
                            "en"
                        ],
                        "reply": {
                            "parent": {
                                "cid": "bafyreiflwzuatocvixdyie5vh6poag4aamy7j33yadfrprxtvglcg7szzi",
                                "uri": "at://did:plc:oisofpd7lj26yvgiivf3lxsi/app.bsky.feed.post/3kvigizd6cm2m"
                            },
                            "root": {
                                "cid": "bafyreiflwzuatocvixdyie5vh6poag4aamy7j33yadfrprxtvglcg7szzi",
                                "uri": "at://did:plc:oisofpd7lj26yvgiivf3lxsi/app.bsky.feed.post/3kvigizd6cm2m"
                            }
                        },
                        "text": "hooray to starter packs"
                    },
                    "replyCount": 2,
                    "repostCount": 0,
                    "likeCount": 11,
                    "indexedAt": "2024-06-22T04:39:58.000Z",
                    "viewer": {
                        "threadMuted": false
                    },
                    "labels": []
                },
                "grandparentAuthor": {
                    "did": "did:plc:oisofpd7lj26yvgiivf3lxsi",
                    "handle": "haileyok.com",
                    "displayName": "hailey",
                    "avatar": "https://cdn.bsky.app/img/avatar/plain/did:plc:oisofpd7lj26yvgiivf3lxsi/bafkreia4lpswywb5yx3gsezqb5io73kt7icw634ks4m4mmbfvp7e62cxku@jpeg",
                    "associated": {
                        "chat": {
                            "allowIncoming": "all"
                        }
                    },
                    "viewer": {
                        "muted": false,
                        "blockedBy": false
                    },
                    "labels": [],
                    "createdAt": "0001-01-01T00:00:00.000Z"
                }
            }
        },
```

**Comment by JoshuaHolme** [comment] 2024-06-23 20:28
Are you able to reproduce it locally?

**Comment by MasterJ93** [comment] 2024-06-24 02:38
I'm able to reproduce it, but it's... weird. I don't see anything in Bluesky's lexicons that suggests that `knownFollowers` would even exist in there. And I don't see anything in my code that would allow for this, either. I'll continue investigating.

**Comment by JoshuaHolme** [comment] 2024-06-24 02:43
Maybe worth reaching out to bluesky devs in the discord?

**Comment by MasterJ93** [comment] 2024-06-24 02:46
No, I found the issue: somewhere down the line, it reaches to `AppBskyLexicon.Actor.ViewerStateDefinition`, which is expected. I accidentally made `knownFollowers` as a required property instead of an optional one. My documentation claims it should be optional, so I knew this was the case, but I simply forgot to add the `?`. I've fixed it and it seems to be working, so I'll add it into the next hotfix.

**Comment by JoshuaHolme** [comment] 2024-06-24 02:48
Nice! Quick turn around too, thank you

**Comment by MasterJ93** [comment] 2024-06-24 03:23
Hotfix has been deployed. Could you check to see if the bug is fixed on your end? If not, please show me the error.

**Comment by MasterJ93** [comment] 2024-06-24 04:10
I've deployed a second hotfix as I found another issue with respect to a property that was required when it should have been optional. I'll have to do an audit to ensure all properties of every model and method are properly marked as optional or required.

Hopefully when I complete the development of the lexicon builder, this will no longer be a problem, but for now, this is what I'll need to contend with. In any case, please let me know if the bugs have been fixed.

**Comment by JoshuaHolme** [comment] 2024-06-24 04:11
Still erroring out, but slightly different error now. Getting the following error:
```
▿ DecodingError
  ▿ keyNotFound : 2 elements
    - .0 : CodingKeys(stringValue: "grandparentAuthor", intValue: nil)
    ▿ .1 : Context
      ▿ codingPath : 3 elements
        - 0 : CodingKeys(stringValue: "feed", intValue: nil)
        ▿ 1 : _JSONKey(stringValue: "Index 5", intValue: 5)
          ▿ rep : Rep
            - index : 5
        - 2 : CodingKeys(stringValue: "reply", intValue: nil)
      - debugDescription : "No value associated with key CodingKeys(stringValue: \"grandparentAuthor\", intValue: nil) (\"grandparentAuthor\")."
      - underlyingError : nil
```

Looks like it's only used on `ReplyReferenceDefinition`, which on main is optional, but in the release isn't

**Comment by JoshuaHolme** [comment] 2024-06-24 04:20
Working now! Thanks for the promptness

**Comment by MasterJ93** [comment] 2024-06-24 04:24
Awesome! I'm closing the issue as completed, but if there are other bugs, please create a new issue.

**Closed by MasterJ93** 2024-06-24 04:24 UTC
Labels: bug
